# Generated by Django 4.1.3 on 2022-11-25 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureSensors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255, verbose_name='Location of the sensor')),
                ('dateMeasurement', models.DateField(default=datetime.date.today, verbose_name='Date of temperature measurement')),
                ('timeMeasurement', models.DateField(default=datetime.time, verbose_name='Time of temperature measurement')),
                ('temperature', models.IntegerField(default=0, verbose_name='Temperature')),
                ('name', models.CharField(max_length=50, verbose_name='Sensor name')),
                ('model', models.CharField(max_length=50, verbose_name='Sensor model')),
                ('group', models.CharField(max_length=50, verbose_name='The group to which the sensor belongs')),
            ],
        ),
    ]
